# .github/workflows/publish.yml

name: Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: pnpm i

      - name: Lint
        run: pnpm turbo lint

      - name: Run Tests with Coverage
        run: pnpm turbo test:coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    if: success()
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: denoland/setup-deno@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          # This is the key change:
          auth-token: ${{ secrets.NPM_TOKEN }}
      - run: pnpm i
      - name: Publish package
        run: pnpm publish --access public --provenance
